library(igraph)
N <- 1000
p <- 0.1
g <- erdos.renyi.game(N, p)
k_medio_e <- mean(degree(g))
k_medio_t <- p*(N-1)
sigma_e <- sd(degree(g))
sigma_t=sqrt(k_medio_t)
x_min <- as.integer(k_medio_e-3*sigma_e)
x_max <- as.integer(k_medio_e+3*sigma_e)
d <- degree_distribution(g)
plot(d, xlim = c(x_min, x_max))
lines(x_min:x_max,dpois(x=x_min:x_max,lambda=k_medio_e),type='l',col="red")
RMSE <- sqrt(mean((d - dpois(x=1:length(d),lambda=k_medio_e))^2))
c_i <- transitivity(g, type = "local", isolates = "NaN")
hist(c_i)
mean(c_i)
mean_distance(g)
log(N)/log(k_medio_e)